import type { SourceCoverageItem } from './types';

export const sourceCoverage: SourceCoverageItem[] = [
  {
    sourcePage: 'Home',
    sourceUrl: 'https://impetusacademy.ng/',
    sourceSections: ['Header', 'Features', 'About', 'Vision/Mission', 'Location/Hours', 'Curriculum', 'Founder message', 'Methodology', 'Testimonials', 'FAQ'],
    destinations: ['/', '/about', '/about/founder', '/academics', '/life-at-impetus', '/contact'],
    status: 'partially-migrated',
    notes: 'Core homepage copy, methodology, vision/mission, testimonials, and FAQ are migrated or centralized. Image-backed sections still need approved school assets.',
  },
  {
    sourcePage: 'Brief History',
    sourceUrl: 'https://impetusacademy.ng/brief-history/',
    sourceSections: ['History narrative', 'Vision/Mission', 'IILA approach', 'Activity-based learning', 'Program summaries'],
    destinations: ['/about/our-story', '/about', '/academics', '/primary-school', '/secondary-school'],
    status: 'partially-migrated',
    notes: 'Founding facts and primary-arm establishment are preserved. Exact historical naming and some phrasing require confirmation.',
  },
  {
    sourcePage: 'Admissions',
    sourceUrl: 'https://impetusacademy.ng/admissions/',
    sourceSections: ['Onboarding process', 'Fees', 'Application steps', 'Documents', 'Bank details', 'Tuition/payment'],
    destinations: ['/admissions', '/primary-school/admissions', '/secondary-school/admissions', '/confirmation-needed'],
    status: 'confirmation-needed',
    notes: 'Process is migrated. Application fee, boarding, bank details, payment instructions, and document requirements are intentionally marked or hidden pending approval.',
  },
  {
    sourcePage: 'Academic',
    sourceUrl: 'https://impetusacademy.ng/academic/',
    sourceSections: ['Curriculum focus', 'Programs'],
    destinations: ['/academics', '/primary-school/kindergarten', '/primary-school/elementary', '/secondary-school/junior-secondary', '/secondary-school/senior-secondary'],
    status: 'migrated',
    notes: 'Repeated curriculum focus is centralized. Program summaries are routed into stage/pathway pages.',
  },
  {
    sourcePage: 'Gallery',
    sourceUrl: 'https://impetusacademy.ng/gallery/',
    sourceSections: ['Gallery framing', 'CTA', 'Curriculum', 'FAQ', 'Testimonials'],
    destinations: ['/gallery', '/life-at-impetus'],
    status: 'pending-assets',
    notes: 'Gallery route exists with consent/classification policy. Real gallery requires approved school imagery and metadata.',
  },
  {
    sourcePage: 'Contact',
    sourceUrl: 'https://impetusacademy.ng/contact/',
    sourceSections: ['Contact details', 'Opening hours', 'Form fields', 'FAQ', 'Testimonials'],
    destinations: ['/contact', '/admissions', 'global footer'],
    status: 'partially-migrated',
    notes: 'Contact details and form shape are migrated. Backend submission and privacy consent remain pending.',
  },
  {
    sourcePage: 'Founder\'s Profile',
    sourceUrl: 'https://impetusacademy.ng/founders-profile/',
    sourceSections: ['Profile intro', 'Story', 'Founder message', 'Vision/Mission'],
    destinations: ['/about/founder', '/'],
    status: 'confirmation-needed',
    notes: 'Profile content is migrated. Exact public name/title, credentials, and portrait need confirmation.',
  },
  {
    sourcePage: 'Proprietor\'s Profile',
    sourceUrl: 'https://impetusacademy.ng/proprietors-profile/',
    sourceSections: ['Profile intro', 'Story', 'Background/expertise', 'Educational philosophy', 'Leadership/impact'],
    destinations: ['/about/proprietor'],
    status: 'confirmation-needed',
    notes: 'Profile content is migrated. Exact title, credentials, portrait, and preferred biography require confirmation.',
  },
  {
    sourcePage: 'Kindergarten Curriculum',
    sourceUrl: 'https://impetusacademy.ng/kindergarten-curriculum/',
    sourceSections: ['Programs', 'Curriculum focus', 'FAQ', 'Testimonials'],
    destinations: ['/primary-school/kindergarten', '/academics'],
    status: 'migrated',
    notes: 'Curriculum groups are migrated without adding age ranges.',
  },
  {
    sourcePage: 'Elementary Curriculum',
    sourceUrl: 'https://impetusacademy.ng/elementary-curriculum/',
    sourceSections: ['Programs', 'Curriculum focus', 'FAQ', 'Testimonials'],
    destinations: ['/primary-school/elementary', '/academics'],
    status: 'confirmation-needed',
    notes: 'Curriculum groups are migrated. Public label Elementary/Primary needs confirmation.',
  },
  {
    sourcePage: 'JSS Curriculum',
    sourceUrl: 'https://impetusacademy.ng/jss-curriculum/',
    sourceSections: ['Programs', 'Curriculum focus', 'FAQ', 'Testimonials'],
    destinations: ['/secondary-school/junior-secondary', '/academics'],
    status: 'migrated',
    notes: 'Curriculum groups are migrated and linked from Secondary and Academics.',
  },
  {
    sourcePage: 'SSS Curriculum-Science',
    sourceUrl: 'https://impetusacademy.ng/sss-curriculum-science/',
    sourceSections: ['Programs', 'Curriculum focus', 'FAQ', 'Testimonials'],
    destinations: ['/secondary-school/senior-secondary/science', '/academics'],
    status: 'migrated',
    notes: 'Science pathway content is migrated into grouped curriculum sections.',
  },
  {
    sourcePage: 'SSS Curriculum-Art',
    sourceUrl: 'https://impetusacademy.ng/sss-curriculum-art/',
    sourceSections: ['Programs', 'Curriculum focus', 'FAQ', 'Testimonials'],
    destinations: ['/secondary-school/senior-secondary/arts', '/academics'],
    status: 'confirmation-needed',
    notes: 'Arts pathway content is tracked. Confirm final public label: Art or Arts.',
  },
  {
    sourcePage: 'SSS Curriculum-Commercial',
    sourceUrl: 'https://impetusacademy.ng/sss-curriculum-commercial/',
    sourceSections: ['Programs', 'Curriculum focus', 'FAQ', 'Testimonials'],
    destinations: ['/secondary-school/senior-secondary/commercial', '/academics'],
    status: 'migrated',
    notes: 'Commercial pathway content is migrated into grouped curriculum sections.',
  },
  {
    sourcePage: 'Shared FAQ and Testimonials',
    sourceUrl: 'Repeated across source pages',
    sourceSections: ['10 FAQ items', '3 testimonials'],
    destinations: ['centralized data in lib/content', '/', '/academics', '/admissions'],
    status: 'centralized',
    notes: 'FAQ and testimonials are stored once and rendered selectively. Testimonials remain general because division attribution is unverified.',
  },
];


export function getSourceCoverage() {
  return sourceCoverage;
}
